apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cloudwatch-exporter
spec:
  ports:
    - port: 9106
      targetPort: 9106
  selector:
    app: {{ .Release.Name }}-cloudwatch-exporter