apiVersion: v2
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts to provide easy to operate end-to-end Kubernetes cluster monitoring with Prometheus using the Prometheus Operator.
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
type: application
maintainers:
  - name: andrewgkew
    email: andrew@quadcorps.co.uk
  - name: gianrubio
    email: gianrubio@gmail.com
  - name: gkarthiks
    email: github.gkarthiks@gmail.com
  - name: GMartinez-Sisti
    email: kube-prometheus-stack@sisti.pt
  - name: jkroepke
    email: github@jkroepke.de
  - name: scottrigby
    email: scott@r6by.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: QuentinBisson
    email: quentin.bisson@gmail.com
name: kube-prometheus-stack
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
version: 66.3.1
appVersion: v0.78.2
kubeVersion: ">=1.19.0-0"
home: https://github.com/prometheus-operator/kube-prometheus
keywords:
  - operator
  - prometheus
  - kube-prometheus
annotations:
  "artifacthub.io/license": Apache-2.0
  "artifacthub.io/operator": "true"
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus

dependencies:
- condition: crds.enabled
  name: crds
  version: "0.0.0"
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://github.com/wow940214/monitoring.git
  version: 5.27.*
- condition: nodeExporter.enabled
  name: prometheus-node-exporter
  repository: https://github.com/wow940214/monitoring.git
  version: 4.42.*
- condition: grafana.enabled
  name: grafana
  repository: https://github.com/wow940214/monitoring.git
  version: 8.6.*
- condition: windowsMonitoring.enabled
  name: prometheus-windows-exporter
  repository: https://github.com/wow940214/monitoring.git
  version: 0.7.*
- condition: prometheusMysqlExporter.enabled
  name: prometheus-mysql-exporter
  repository: https://github.com/wow940214/monitoring.git
  version: 0.7.*
- condition: prometheusNginxExporter.enabled
  name: prometheus-nginx-exporter
  repository: https://github.com/wow940214/monitoring.git
  version: 0.10.*
- condition: prometheusPushgateway.enabled
  name: prometheus-pushgateway
  repository: https://github.com/wow940214/monitoring.git
  version: 1.16.*
- condition: prometheusCloudwatchExporter.enabled
  name: prometheus-cloudwatch-exporter
  repository: https://github.com/wow940214/monitoring.git
  version: 0.23.*
